---

- name: ensure we have git installed (srsly?)
  apt: pkg=git

- name: ensures the app_path exists
  file: path={{ app_path }}
        mode=0755
        owner=root
        state=directory

- name: Pull latest version from git repository
  git: repo={{ git_repo }}
       dest={{ app_path }}
       version={{ git_branch }}
       update=yes
  tags: git


