---

app_host: http://{{ sitename }}.{{ master_host }}
git_branch: master
git_repo: https://github.com/uems/gateway.git
app_path: /opt/gateway
port: 2000
backup: false
sitename: gateway
webport: 80
certificate_hours: 36
