---

- name: install apache
  apt: pkg=apache2
       state=installed

- name: Create an apache site named certs
  template: src=apache_site_gateway.j2
            dest=/etc/apache2/sites-available/gateway

- name: Enable proxy and proxy_http
  command: a2enmod proxy proxy_http

- name: Disable apache site default
  command: a2dissite default

- name: Enable apache site gateway
  command: a2ensite gateway
  notify: restart apache2
