---

- name: configures the gateway for this environment
  tags: config
  template: src=config.js.j2
            dest={{ app_path }}/lib/config.js
            mode=0755
  notify:
    - restart gateway

- name: creates the service for gateway grid
  tags:
    - gateway
    - config
  template: src=gateway.j2
            dest=/etc/init.d/gateway
            mode=0755
  notify:
    - restart gateway

- name: ensures gateway service is enabled and running
  tags:
    - gateway
    - restart
  service: name=gateway
           enabled=yes
           state=restarted
